import mygirl from './mygirl.png'
import black from './black.png'
import victor from './victor.png'
import myguy from './myguy.png'
import girl2 from './girl2.png'
import sit from './sit.png'
import kidss from './kidss.png'
import big from './big.png'
import sm from './sm.png'
import white from './white.png'
import pant from './pant.png'
import d from './d.png'
import bbb from './bbb.png'
import arrow from './Arrow.png'
import kkk from './kkk.png'
import red from './red.png'
import views from './views.png'
import hug from './hug.png'
import com from './com.png'
import blue from './blue.png'
import trust from './trust.png'



 export { mygirl, black, victor, myguy, girl2,sit, kidss, big,sm ,white, pant, d, bbb ,arrow, kkk, red, views, hug,com,blue, trust }